cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:products_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:products_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views
from orders.views import order_create, EsewaRequestView, EsewaVerifyView, req_quotation

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),
    path("request-quotation/",views.req_quotation, name="request_quotation" )

    
]

vistaar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls.conf import re_path
from products.views import HomeView,category_detail,privacy_policy,terms_conditions
from django.conf import settings
from django.conf.urls.static import static
from reviews.views import submit_review
from products.views import filter_data

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', HomeView.as_view(), name='home'),
    path('products/', include('products.urls')),
    path('supplier/', include('suppliers.urls')),
    path('submit_review/<int:product_id>',submit_review,name='submit_review'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('<int:id>/<slug:slug>/', category_detail,name='category_detail'),
    path('privacy-policy', privacy_policy,name='privacy_policy'),
    path('terms-conditions', terms_conditions,name='terms_conditions'),
    path("filter-data/",filter_data,name="filter_data"),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from products.models import Products
from django.contrib.auth.models import User

# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def get_total_price(self):
        return float(self.quantity * self.product.price)

    price = models.FloatField(default=get_total_price)

    def __str__(self):
        return self.user.username

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

    


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Products
from .cart import Cart
from .forms import CartAddProductForm
from account.models import Profile


@require_POST
def cart_add(request, products_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=products_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(products=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, products_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=products_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    if request.user.is_authenticated:
        current_user = request.user
        user_profile = Profile.objects.filter(user=current_user).first()
    else:
        user_profile = 0
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    return render(request, 'cart/detail.html', {'cart': cart,'user_profile':user_profile})

templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}
<h1>Your shopping cart</h1>
<table class='cart'>
<thead>
<tr>
<th>Image</th>
<th>Product</th>
<th>Quantity</th>
<th>Remove</th>
<th>Unit price</th>
<th>Price</th>
</tr>
</thead>
<tbody>
{% for item in cart %}
{% with product=item.product %}
<tr>
<td>
<a href="{{ product.get_absolute_url }}">
<!--img src="{% if product.image %}{{ product.image.url }}
{% else %}{% static "img/no_image.png" %}{% endif %}"-->
</a>
</td>
<td>{{ product.product_name }}</td>
<td>
    <form action="{% url "cart:cart_add" product.id %}" method="post">
    {{ item.update_quantity_form.quantity }}
    {{ item.update_quantity_form.override }}
    <input type="submit" value="Update">
    {% csrf_token %}
    </form>
    </td>
    
<td>
<form action="{% url "cart:cart_remove" product.id %}"
method="post">
<input type="submit" value="Remove">
{% csrf_token %}
</form>
</td>
<td class="num">${{ item.price }}</td>
<td class="num">${{ item.total_price }}</td>
</tr>
{% endwith %}
{% endfor %}
<tr class="total">
    <td>Total</td>
    <td colspan="4"></td>
    <td class="num">${{ cart.get_total_price }}</td>
    </tr>
    </tbody>
    </table>
    <p class="text-right">
    <a href="{% url "home" %}" class="button
    light">Continue shopping</a>
    {% if request.user.is_authenticated %}
    {% if user_profile.account_type == 'Retailer' %}
    <a href="{% url "orders:order_create" %}" class="button">Checkout</a>
    {% elif user_profile.account_type == 'Supplier' %}
    <a href="{% url "logout" %}" class="button">Create a retailer account to shop</a>
    {% elif user_profile.account_type == None %}
    <a href="{% url "dashboard" %}" class="button">Complete your profile as a retailer</a>
    {% endif %}
    {% else %}
    <a href="{% url "login" %}" class="button">Login to shop</a>
    {% endif %}
    </p>
    {% endblock %}
    